-- Populate tarot cards (Major Arcana)
INSERT INTO tarot_cards (
    number,
    name,
    alternative_names,
    arcana,
    element,
    suit,
    meaning_key,
    meaning_upright,
    meaning_reversed,
    description,
    image_url
) VALUES
(0, 
'The Fool', 
'The Jester, The Idiot', 
'Major', 
'Air', 
NULL,
'innocence, risk, beginnings', 
'beginnings, innocence, spontaneity, a free spirit', 
'holding back, recklessness, risk-taking', 
'', 
'images/major_arcana/the_fool.jpg'),
(1, 'The Magician', 'The Magus, The Juggler, The Mountebank', 'Major', 'Air, Ether, Quintessence', NULL, 
'action, creativity, success', 
'manifestation, resourcefulness, power, inspired action', 
'manipulation, poor planning, untapped talents', 
'', 
'images/major_arcana/the_magician.jpg'),
(2, 'The High Priestess', 'The Papess, The Oracle', 'Major', 'Water', NULL, 
'secrets, wisdom, intuition', 
'intuition, sacred knowledge, divine feminine, the subconscious mind', 
'secrets, disconnected from intuition, withdrawal and silence', 
'', 
'images/major_arcana/the_high_priestess.jpg'),
(3, 'The Empress', 'The Mother', 'Major', 'Earth', NULL, 
'abundance, generosity, creativity, fertility', 
'femininity, beauty, nature, nurturing, abundance', 
'creative block, dependence on others', 
'', 
'images/major_arcana/the_empress.jpg'),
(4, 'The Emperor', 'The Grandfather', 'Major', 'Fire', NULL, 
'control, security, order, ambition', 
'authority, establishment, structure, paternity', 
'domination, excessive control, rigidity, inflexibility, lack of discipline', 
'', 
'images/major_arcana/the_emperor.jpg'),
(5, 'The Hierophant', 'The High Priest, The Pope', 'Major', 'Earth', NULL, 
'education, unity, spiritual, direction', 
'spiritual wisdom, religious beliefs, conformity, tradition, institutions', 
'personal beliefs, freedom, challenging the status quo', 
'', 
'images/major_arcana/the_hierophant.jpg'),
(6, 'The Lovers', 'The Lover, Love', 'Major', 'Air', NULL, 
'love and relationships, maturity, decisions', 
'love, harmony, relationships, values alignment, choices', 
'self-love, disharmony, imbalance, misalignment of values', 
'', 
'images/major_arcana/the_lovers.jpg'),
(7, 'The Chariot', 'Victory', 'Major', 'Water', NULL, 
'determination, journey, victory', 
'control, willpower, success, action, determination', 
'self-discipline, opposition, lack of direction', 
'', 
'images/major_arcana/the_chariot.jpg'),
(8, 'Strength', 'Fortitude, Force', 'Major', 'Fire', NULL, 
'patience, tension, strength', '
strength, courage, persuasion, influence, compassion', 
'inner strength, self-doubt, low energy, raw emotion', 
'', 
'images/major_arcana/strength.jpg'),
(9, 'The Hermit', 'The Old Man, Time, The Poor Man', 'Major', 'Earth', NULL, 
'healing, self-exploration', 
'soul-searching, introspection, being alone, inner guidance', 
'isolation, loneliness, withdrawal', 
'', 
'images/major_arcana/the_hermit.jpg'),
(10, 'Wheel of Fortune', 'Fate, Destiny, The Wheel', 'Major', 'Fire', NULL,
'fate, change, intuition', 
'good luck, karma, life cycles, destiny, a turning point', 
'bad luck, resistance to change, breaking cycles', 
'', 
'images/major_arcana/wheel_of_fortune.jpg'),
(11, 'Justice', 'Adjustment', 'Major', 'Air', NULL, 
'balance, perception, objectivity', 
'justice, fairness, truth, cause and effect, law', 
'unfairness, lack of accountability, dishonesty', 
'', 
'images/major_arcana/justice.jpg'),
(12, 'The Hanged Man', 'The Traitor', 'Major', 'Water', NULL, 
'waiting, sacrifice, enlightenment', 
'pause, surrender, letting go, new perspectives', 
'delays, resistance, stalling, indecision', 
'', 
'images/major_arcana/the_hanged_man.jpg'),
(13, 'Death', 'Mortality, Transformation, Thirteen', 'Major', 'Water', NULL, 
'transformation, change', 
'endings, change, transformation, transition', 
'resistance to change, personal transformation, inner purging', 
'', 
'images/major_arcana/death.jpg'),
(14, 'Temperance', 'Art', 'Major', 'Fire', NULL, 
'moderation, reconciliation, healing, angelic guidance', 
'balance, moderation, patience, purpose', 
'imbalance, excess, self-healing, re-alignment', 
'', 
'images/major_arcana/temperance.jpg'),
(15, 'The Devil', 'Pan, Temptation', 'Major', 'Earth', NULL, 
'enslavement, temptation', 
'shadow self, attachment, addiction, restriction, sexuality', 
'releasing limiting beliefs, exploring dark thoughts, detachment', 
'', 
'images/major_arcana/the_devil.jpg'),
(16, 'The Tower', 'The House of God, Fate, The Lightning', 'Major', 'Fire', NULL, 
'destruction, enlightenment', 
'sudden change, upheaval, chaos, revelation, awakening', 
'personal transformation, fear of change, averting disaster', 
'', 
'images/major_arcana/the_tower.jpg'),
(17, 'The Star', 'Hope, The Stars', 'Major', 'Air', NULL, 
'hope, guidance, inspiration, creativity',
'hope, faith, purpose, renewal, spirituality', 
'lack of faith, despair, self-trust, disconnection',
'', 
'images/major_arcana/the_star.jpg'),
(18, 'The Moon', 'Illusion, Luna', 'Major', 'Water', NULL, 
'illusion, dreams, crisis', 
'illusion, fear, anxiety, subconscious, intuition', 
'release of fear, repressed emotion, inner confusion', 
'', 
'images/major_arcana/the_moon.jpg'),
(19, 'The Sun', 'The Children', 'Major', 'Fire', NULL, 
'success, good health, holiday', 
'positivity, fun, warmth, success, vitality', 
'inner child, feeling down, overly optimistic', 
'', 
'images/major_arcana/the_sun.jpg'),
(20, 'Judgement', 'The Angel, Fame, Time', 'Major', 'Fire', NULL, 
'assessment, letting go of the past', 
'judgement, rebirth, inner calling, absolution', 
'self-doubt, inner critic, ignoring the call', 
'', 
'images/major_arcana/judgement.jpg'),
(21, 'The World', 'The Universe', 'Major', 'Earth', NULL, 
'completion, success, reward, joy', 
'completion, integration, accomplishment, travel', 
'seeking personal closure, short-cuts, delays', 
'', 
'images/major_arcana/the_world.jpg')
AS new
ON DUPLICATE KEY UPDATE
    number           = new.number,
    alternative_names = new.alternative_names,
    arcana           = new.arcana,
    element           = new.element,
    suit              = new.suit,
    meaning_key       = new.meaning_key,
    meaning_upright   = new.meaning_upright,
    meaning_reversed  = new.meaning_reversed,
    description       = new.description,
    image_url         = new.image_url;