-- Populate tarot cards (Minor Arcana)

INSERT INTO tarot_cards (
    number,
    name,
    alternative_names,
    arcana,
    element,
    suit,
    meaning_key,
    meaning_upright,
    meaning_reversed,
    description,
    image_url
) VALUES
-- WANDS (Fire)
(1, 'Ace of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'inspiration, creation, potential',
 'inspiration, new opportunities, growth, potential',
 'delays, lack of direction, distractions', 
 '', 
 'images/minor_arcana/wands/1_wands.jpg'),
(2, 'Two of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'planning, decisions, progress',
 'future planning, progress, decisions, discovery',
 'fear of change, playing safe, bad planning', 
 '', 
 'images/minor_arcana/wands/2_wands.jpg'),
(3, 'Three of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'expansion, foresight, leadership',
 'expansion, foresight, overseas opportunities',
 'obstacles, delays, frustration', 
 '', 
 'images/minor_arcana/wands/3_wands.jpg'),
(4, 'Four of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'celebration, harmony, home',
 'celebration, joy, harmony, relaxation',
 'tension, conflict, lack of support', 
 '', 
 'images/minor_arcana/wands/4_wands.jpg'),
(5, 'Five of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'conflict, competition, tension',
 'competition, conflict, disagreements',
 'inner conflict, avoidance of conflict', 
 '', 
 'images/minor_arcana/wands/5_wands.jpg'),
(6, 'Six of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'victory, recognition, success',
 'victory, success, public reward',
 'self-doubt, lack of recognition', 
 '', 
 'images/minor_arcana/wands/6_wands.jpg'),
(7, 'Seven of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'defense, perseverance, challenge',
 'defending your position, perseverance',
 'giving up, overwhelmed, defensiveness', 
 '', 
 'images/minor_arcana/wands/7_wands.jpg'),
(8, 'Eight of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'movement, speed, action',
 'rapid action, movement, progress',
 'delays, frustration, resistance', 
 '', 
 'images/minor_arcana/wands/8_wands.jpg'),
(9, 'Nine of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'resilience, persistence, boundaries',
 'resilience, courage, persistence',
 'exhaustion, fatigue, defensiveness', 
 '', 
 'images/minor_arcana/wands/9_wands.jpg'),
(10, 'Ten of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'burden, responsibility, stress',
 'burden, responsibility, hard work',
 'burnout, overwhelm, release', 
 '', 
 'images/minor_arcana/wands/10_wands.jpg'),
(11, 'Page of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'exploration, enthusiasm, discovery',
 'enthusiasm, exploration, discovery',
 'lack of direction, procrastination', 
 '', 
 'images/minor_arcana/wands/11_wands.jpg'),
(12, 'Knight of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'action, adventure, impulsiveness',
 'energy, passion, inspired action',
 'recklessness, impatience, frustration', 
 '', 
 'images/minor_arcana/wands/12_wands.jpg'),
(13, 'Queen of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'confidence, determination, warmth',
 'confidence, determination, vibrancy',
 'insecurity, jealousy, selfishness', 
 '', 
 'images/minor_arcana/wands/13_wands.jpg'),
(14, 'King of Wands', NULL, 'Minor', 'Fire', 'Wands',
 'leadership, vision, authority',
 'natural leader, vision, entrepreneurship',
 'impulsiveness, arrogance, rigidity', 
 '', 
 'images/minor_arcana/wands/14_wands.jpg'),
-- CUPS (Water)
(1, 'Ace of Cups', NULL, 'Minor', 'Water', 'Cups',
 'love, compassion, creativity',
 'new feelings, emotional awakening, love',
 'emotional loss, blocked creativity', 
 '', 
 'images/minor_arcana/cups/1_cups.jpg'),
(2, 'Two of Cups', NULL, 'Minor', 'Water', 'Cups',
 'connection, unity, partnership',
 'partnership, mutual attraction, unity',
 'imbalance, tension, miscommunication', 
 '', 
 'images/minor_arcana/cups/2_cups.jpg'),
(3, 'Three of Cups', NULL, 'Minor', 'Water', 'Cups',
 'friendship, celebration, community',
 'celebration, friendship, collaboration',
 'overindulgence, gossip, isolation', 
 '', 
 'images/minor_arcana/cups/3_cups.jpg'),
(4, 'Four of Cups', NULL, 'Minor', 'Water', 'Cups',
 'apathy, contemplation, discontent',
 'meditation, contemplation, reevaluation',
 'missed opportunities, withdrawal', 
 '', 
 'images/minor_arcana/cups/4_cups.jpg'),
(5, 'Five of Cups', NULL, 'Minor', 'Water', 'Cups',
 'loss, grief, disappointment',
 'loss, grief, regret',
 'acceptance, moving on, forgiveness', 
 '', 
 'images/minor_arcana/cups/5_cups.jpg'),
(6, 'Six of Cups', NULL, 'Minor', 'Water', 'Cups',
 'nostalgia, memories, innocence',
 'nostalgia, childhood memories, joy',
 'living in the past, stagnation', 
 '', 
 'images/minor_arcana/cups/6_cups.jpg'),
(7, 'Seven of Cups', NULL, 'Minor', 'Water', 'Cups',
 'choices, illusion, fantasy',
 'choices, opportunities, imagination',
 'clarity, realism, decisive action', 
 '', 
 'images/minor_arcana/cups/7_cups.jpg'),
(8, 'Eight of Cups', NULL, 'Minor', 'Water', 'Cups',
 'abandonment, withdrawal, introspection',
 'walking away, seeking deeper meaning',
 'fear of change, stagnation', 
 '', 
 'images/minor_arcana/cups/8_cups.jpg'),
(9, 'Nine of Cups', NULL, 'Minor', 'Water', 'Cups',
 'satisfaction, contentment, pleasure',
 'contentment, satisfaction, gratitude',
 'greed, dissatisfaction, indulgence', 
 '', 
 'images/minor_arcana/cups/9_cups.jpg'),
(10, 'Ten of Cups', NULL, 'Minor', 'Water', 'Cups',
 'harmony, happiness, alignment',
 'emotional fulfillment, harmony',
 'broken relationships, misalignment', 
 '', 
 'images/minor_arcana/cups/10_cups.jpg'),
(11, 'Page of Cups', NULL, 'Minor', 'Water', 'Cups',
 'intuition, curiosity, creativity',
 'creative beginnings, intuition',
 'emotional immaturity, insecurity', 
 '', 
 'images/minor_arcana/cups/11_cups.jpg'),
(12, 'Knight of Cups', NULL, 'Minor', 'Water', 'Cups',
 'romance, charm, imagination',
 'romantic gestures, idealism',
 'unrealistic expectations, moodiness', 
 '', 
 'images/minor_arcana/cups/12_cups.jpg'),
(13, 'Queen of Cups', NULL, 'Minor', 'Water', 'Cups',
 'compassion, empathy, calm',
 'emotional stability, compassion',
 'emotional insecurity, dependence', 
 '', 
 'images/minor_arcana/cups/13_cups.jpg'),
(14, 'King of Cups', NULL, 'Minor', 'Water', 'Cups',
 'balance, diplomacy, control',
 'emotional balance, wisdom',
 'emotional manipulation, volatility', 
 '', 
 'images/minor_arcana/cups/14_cups.jpg'),
-- SWORDS (Air)
(1, 'Ace of Swords', NULL, 'Minor', 'Air', 'Swords',
 'clarity, truth, breakthrough',
 'clarity, truth, new ideas',
 'confusion, chaos, lack of focus', 
 '', 
 'images/minor_arcana/swords/1_swords.jpg'),
(2, 'Two of Swords', NULL, 'Minor', 'Air', 'Swords',
 'indecision, stalemate, avoidance',
 'difficult decisions, balance',
 'confusion, information overload', 
 '', 
 'images/minor_arcana/swords/2_swords.jpg'),
(3, 'Three of Swords', NULL, 'Minor', 'Air', 'Swords',
 'heartbreak, sorrow, pain',
 'heartbreak, emotional pain',
 'healing, forgiveness, recovery', 
 '', 
 'images/minor_arcana/swords/3_swords.jpg'),
(4, 'Four of Swords', NULL, 'Minor', 'Air', 'Swords',
 'rest, recovery, contemplation',
 'rest, recuperation, meditation',
 'burnout, restlessness', 
 '', 
 'images/minor_arcana/swords/4_swords.jpg'),
(5, 'Five of Swords', NULL, 'Minor', 'Air', 'Swords',
 'conflict, betrayal, tension',
 'conflict, win-at-all-costs',
 'reconciliation, compromise', 
 '', 
 'images/minor_arcana/swords/5_swords.jpg'),
(6, 'Six of Swords', NULL, 'Minor', 'Air', 'Swords',
 'transition, healing, change',
 'moving on, transition, relief',
 'resistance to change, baggage', 
 '', 
 'images/minor_arcana/swords/6_swords.jpg'),
(7, 'Seven of Swords', NULL, 'Minor', 'Air', 'Swords',
 'deception, strategy, secrecy',
 'betrayal, deception, strategy',
 'coming clean, accountability', 
 '', 
 'images/minor_arcana/swords/7_swords.jpg'),
(8, 'Eight of Swords', NULL, 'Minor', 'Air', 'Swords',
 'restriction, fear, self-doubt',
 'self-imposed restriction, fear',
 'empowerment, liberation', 
 '', 
 'images/minor_arcana/swords/8_swords.jpg'),
(9, 'Nine of Swords', NULL, 'Minor', 'Air', 'Swords',
 'anxiety, fear, nightmares',
 'anxiety, worry, fear',
 'hope, release, recovery', 
 '', 
 'images/minor_arcana/swords/9_swords.jpg'),
(10, 'Ten of Swords', NULL, 'Minor', 'Air', 'Swords',
 'betrayal, endings, collapse',
 'painful endings, betrayal',
 'recovery, regeneration', 
 '', 
 'images/minor_arcana/swords/10_swords.jpg'),
(11, 'Page of Swords', NULL, 'Minor', 'Air', 'Swords',
 'curiosity, communication, vigilance',
 'new ideas, curiosity, learning',
 'deception, manipulation', 
 '', 
 'images/minor_arcana/swords/11_swords.jpg'),
(12, 'Knight of Swords', NULL, 'Minor', 'Air', 'Swords',
 'ambition, action, haste',
 'ambition, determination, action',
 'impulsiveness, recklessness', 
 '', 
 'images/minor_arcana/swords/12_swords.jpg'),
(13, 'Queen of Swords', NULL, 'Minor', 'Air', 'Swords',
 'clarity, independence, honesty',
 'clear thinking, independence',
 'coldness, bitterness', 
 '', 
 'images/minor_arcana/swords/13_swords.jpg'),
(14, 'King of Swords', NULL, 'Minor', 'Air', 'Swords',
 'intellect, authority, truth',
 'mental clarity, authority',
 'manipulation, tyranny', 
 '', 
 'images/minor_arcana/swords/14_swords.jpg'),
-- PENTACLES (Earth)
(1, 'Ace of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'prosperity, opportunity, stability',
 'new financial opportunity, abundance',
 'missed opportunity, scarcity', 
 '', 
 'images/minor_arcana/pentacles/1_pentacles.jpg'),
(2, 'Two of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'balance, adaptability, priorities',
 'balance, adaptability, time management',
 'overcommitment, disorganization', 
 '', 
 'images/minor_arcana/pentacles/2_pentacles.jpg'),
(3, 'Three of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'collaboration, learning, teamwork',
 'teamwork, collaboration, skill',
 'lack of teamwork, disorganization', 
 '', 
 'images/minor_arcana/pentacles/3_pentacles.jpg'),
(4, 'Four of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'control, security, possessiveness',
 'financial security, conservation',
 'greed, insecurity, loss', 
 '', 
 'images/minor_arcana/pentacles/4_pentacles.jpg'),
(5, 'Five of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'hardship, poverty, isolation',
 'financial loss, hardship',
 'recovery, assistance, hope', 
 '', 
 'images/minor_arcana/pentacles/5_pentacles.jpg'),
(6, 'Six of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'generosity, sharing, balance',
 'generosity, charity, balance',
 'debt, selfishness, imbalance', 
 '', 
 'images/minor_arcana/pentacles/6_pentacles.jpg'),
(7, 'Seven of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'patience, assessment, growth',
 'long-term growth, patience',
 'impatience, lack of reward', 
 '',
 'images/minor_arcana/pentacles/7_pentacles.jpg'),
(8, 'Eight of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'skill, diligence, craftsmanship',
 'apprenticeship, mastery, dedication',
 'perfectionism, lack of focus', 
 '', 
 'images/minor_arcana/pentacles/8_pentacles.jpg'),
(9, 'Nine of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'luxury, independence, reward',
 'self-sufficiency, abundance',
 'financial dependence, setbacks', 
 '', 
 'images/minor_arcana/pentacles/9_pentacles.jpg'),
(10, 'Ten of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'wealth, legacy, security',
 'financial security, legacy',
 'loss, instability', 
 '', 
 'images/minor_arcana/pentacles/10_pentacles.jpg'),
(11, 'Page of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'opportunity, learning, growth',
 'new opportunities, learning',
 'lack of commitment, procrastination', 
 '', 
 'images/minor_arcana/pentacles/11_pentacles.jpg'),
(12, 'Knight of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'responsibility, routine, diligence',
 'hard work, reliability',
 'stagnation, laziness', 
 '',
 'images/minor_arcana/pentacles/12_pentacles.jpg'),
(13, 'Queen of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'nurturing, practicality, security',
 'practicality, nurturing, abundance',
 'self-neglect, imbalance', 
 '', 
 'images/minor_arcana/pentacles/13_pentacles.jpg'),
(14, 'King of Pentacles', NULL, 'Minor', 'Earth', 'Pentacles',
 'wealth, leadership, stability',
 'financial success, leadership',
 'greed, stubbornness', 
 '', 
 'images/minor_arcana/pentacles/14_pentacles.jpg')
AS new
ON DUPLICATE KEY UPDATE
    number            = new.number,
    alternative_names = new.alternative_names,
    arcana            = new.arcana,
    element            = new.element,
    suit               = new.suit,
    meaning_key        = new.meaning_key,
    meaning_upright    = new.meaning_upright,
    meaning_reversed   = new.meaning_reversed,
    description        = new.description,
    image_url          = new.image_url;
